/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ui;

import com.poly.model.QuanLiSach;
import com.poly.utils.XDialog;
import com.poly.utils.XShare;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;

/**
 *
 * @author CuongNX
 */
public class ModelBoxSach extends javax.swing.JPanel {

    /**
     * Creates new form ModelBoxSach
     */
    String url;

    public ModelBoxSach() {
        initComponents();
    }

    public ModelBoxSach(QuanLiSach s) {
        initComponents();
        lblTenSach.setText(s.getTenSach());
        lblHinh.setIcon(ResizeImage(String.valueOf(XShare.readLogo(s.getHinh().split(",")[0]))));
        url = s.getUrl();
        jTextArea1.setText(s.getNoiDung());
        jTextArea1.setLineWrap(true);
    }

//    SachUI.MainPanel.removeAll();
//        SachUI.MainPanel.add(new Form_ChiTietSach());
//        SachUI.MainPanel.repaint();
//        SachUI.MainPanel.revalidate();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTenSach = new javax.swing.JLabel();
        lblHinh = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(205, 240, 234));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTenSach.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblTenSach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenSach.setText("jLabel1");
        lblTenSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTenSachMouseClicked(evt);
            }
        });
        lblTenSach.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblTenSachComponentHidden(evt);
            }
        });

        lblHinh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhMouseClicked(evt);
            }
        });

        jTextArea1.setBackground(new java.awt.Color(205, 240, 234));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jTextArea1.setCaretColor(new java.awt.Color(205, 240, 234));
        jTextArea1.setDisabledTextColor(new java.awt.Color(205, 240, 234));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(lblHinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHinh, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblTenSachComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblTenSachComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTenSachComponentHidden

    private void lblHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhMouseClicked
        // TODO add your handling code here:
//        SachUI.MainPanel.removeAll();
//        SachUI.MainPanel.add(new Form_ChiTietSach());
//        SachUI.MainPanel.repaint();
//        SachUI.MainPanel.revalidate();
        openpdf("file\\" + url);
//            openpdf("file//");
    }//GEN-LAST:event_lblHinhMouseClicked

    private void lblTenSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTenSachMouseClicked
        // TODO add your handling code here:
        openpdf("file\\" + url);

    }//GEN-LAST:event_lblTenSachMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblHinh;
    private javax.swing.JLabel lblTenSach;
    // End of variables declaration//GEN-END:variables

    private ImageIcon ResizeImage(String ImagePath) {
//        System.out.println(ImagePath);
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();

        Image newImg = img.getScaledInstance(250, 300, Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    void openpdf(String file) {
        try {
            Desktop.getDesktop().browse(new File(file).toURI());
        } catch (IOException ex) {
            XDialog.alert(this, "Can't find url file!");
            System.out.println(ex);
        }
    }
}
