/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.ui;

import com.poly.dao.NhaXuatBanDAO;
import com.poly.dao.QuanLiSachDAO;
import com.poly.dao.TacGiaDAO;
import com.poly.dao.TheLoaiDAO;
import com.poly.model.NhaXuatBan;
import com.poly.model.QuanLiSach;
import com.poly.model.TacGia;
import com.poly.model.TheLoai;
import com.poly.utils.XDate;
import com.poly.utils.XDialog;
import com.poly.utils.XShare;
import java.awt.CardLayout;
import java.awt.Font;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author CuongNX
 */
public class QuanLiSachUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLiSachUI
     */
    private CardLayout cardLayout;
    int index = 0;
    QuanLiSachDAO dao = new QuanLiSachDAO();
    DefaultComboBoxModel modelTheLoai, modelTG, modelNXB;
    int stt = 0;

    public QuanLiSachUI() {
        initComponents();
        init();
        setStatus(true);
        cboPub.removeAllItems();
        cboCategory.removeAllItems();
        cboAuthor1.removeAllItems();
        txtContent.setLineWrap(true);
        this.loadcbbNXB();
        this.loadcbbTenTheLoai();
        this.loadcbbTacGia();
        this.load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblHinh1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cboCategory = new javax.swing.JComboBox<>();
        cboPub = new javax.swing.JComboBox<>();
        cboAuthor1 = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        btnlui = new javax.swing.JButton();
        btnTien = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(205, 240, 234));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 623));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDanhSach.setBackground(new java.awt.Color(205, 240, 234));
        tblDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Name", "Category ID", "Author", "Publisher", "Date Added", "Amount", "Content", "Image"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSach.setFocusable(false);
        tblDanhSach.setRowHeight(30);
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSach);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 144, 500, 390));

        jPanel5.setBackground(new java.awt.Color(205, 240, 234));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Book ID:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 57, 39));

        txtID.setBackground(new java.awt.Color(205, 240, 234));
        txtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtID.setBorder(null);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel5.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 230, 39));

        jPanel2.setBackground(new java.awt.Color(205, 240, 234));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblHinh1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinh1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblHinh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblHinh1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 24, 190, 230));

        txtName.setBackground(new java.awt.Color(205, 240, 234));
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtName.setBorder(null);
        jPanel5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 230, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Name:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 57, 39));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Publisher:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 70, 39));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Category:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 70, 39));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Author:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 306, 70, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Date Added:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 297, -1, 39));

        jDateChooser.setBackground(new java.awt.Color(205, 240, 234));
        jDateChooser.setDate(new java.util.Date(1667551026000L));
        jDateChooser.setDateFormatString("dd-MM-yyyy");
        jDateChooser.setFocusable(false);
        jDateChooser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 297, 163, 39));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Content:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 70, 39));

        txtContent.setBackground(new java.awt.Color(205, 240, 234));
        txtContent.setColumns(20);
        txtContent.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtContent.setRows(5);
        jScrollPane1.setViewportView(txtContent);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 491, 50));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 230, 10));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 230, 10));

        cboCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCategory.setFocusable(false);
        jPanel5.add(cboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 160, 40));

        cboPub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboPub.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPub.setFocusable(false);
        cboPub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPubActionPerformed(evt);
            }
        });
        jPanel5.add(cboPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 230, 40));

        cboAuthor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboAuthor1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboAuthor1.setFocusable(false);
        jPanel5.add(cboAuthor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, 40));

        txtAmount.setBackground(new java.awt.Color(205, 240, 234));
        txtAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAmount.setText("0");
        txtAmount.setBorder(null);
        jPanel5.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 160, 39));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 160, 10));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Amount:");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 57, 39));

        btnlui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlui.setText("<<");
        btnlui.setFocusable(false);
        btnlui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluiActionPerformed(evt);
            }
        });
        jPanel5.add(btnlui, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        btnTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTien.setText(">>");
        btnTien.setFocusable(false);
        btnTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTienActionPerformed(evt);
            }
        });
        jPanel5.add(btnTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Url:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 57, 39));

        txtUrl.setBackground(new java.awt.Color(205, 240, 234));
        txtUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUrl.setBorder(null);
        jPanel5.add(txtUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 160, 39));
        jPanel5.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 160, 10));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 510, 490));

        jPanel6.setBackground(new java.awt.Color(205, 240, 234));

        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSearch.setText("Search:");

        txtFind.setBackground(new java.awt.Color(205, 240, 234));
        txtFind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFind.setBorder(null);
        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFindKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/Search.png"))); // NOI18N
        btnSearch.setText("Find");
        btnSearch.setFocusable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator7)
                    .addComponent(txtFind, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 540, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BOOKS MANAGEMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 34, 1091, -1));

        btnNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_add_24px.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.setFocusable(false);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel1.add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, 39));

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_Add_properies_24px.png"))); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.setFocusable(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, 39));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_update_24px.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setFocusable(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 570, -1, 39));

        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_Delete_24px.png"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.setFocusable(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, 39));

        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/export.png"))); // NOI18N
        btnPrint.setText("PRINT TABLE");
        btnPrint.setFocusable(false);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 560, -1, 39));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        if (evt.getClickCount() == 2) {
            this.index = tblDanhSach.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
                cboPub.setSelectedItem(tblDanhSach.getValueAt(index, 2).toString());
                cboCategory.setSelectedItem(tblDanhSach.getValueAt(index, 2).toString());
                cboAuthor1.setSelectedItem(tblDanhSach.getValueAt(index, 2).toString());
            }
        }

    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        print();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cboPubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPubActionPerformed

    private void txtFindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            load();
            clear();
        }
    }//GEN-LAST:event_txtFindKeyPressed

    private void btnluiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluiActionPerformed
        // TODO add your handling code here:
        --stt;
        remote();
    }//GEN-LAST:event_btnluiActionPerformed

    private void btnTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTienActionPerformed
        // TODO add your handling code here:
        ++stt;
        remote();
    }//GEN-LAST:event_btnTienActionPerformed

    private void lblHinh1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinh1MouseClicked
        // TODO add your handling code here:
        selectImage();

    }//GEN-LAST:event_lblHinh1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTien;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnlui;
    private javax.swing.JComboBox<String> cboAuthor1;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JComboBox<String> cboPub;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblHinh1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtContent;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtUrl;
    // End of variables declaration//GEN-END:variables

    private void init() {
        tblDanhSach.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        tblDanhSach.setDefaultEditor(Object.class, null);
    }

    private boolean isValidate(QuanLiSach s) {
        if (s.getMaSach().equals("")) {
            XDialog.alert(this, "Id Book can't be empty");
            txtID.requestFocus();
            return false;
        }
        if (s.getTenSach().equals("")) {
            XDialog.alert(this, "Name Book can't be empty");
            txtName.requestFocus();
            return false;
        }
        if (s.getNXB().equals("")) {
            XDialog.alert(this, "Publisher can't be empty");
            cboPub.requestFocus();
            return false;
        }
        if (s.getLoai().equals("")) {
            XDialog.alert(this, "Category can't be empty");
            cboCategory.requestFocus();
            return false;
        }
        if (s.getTacGia().equals("")) {
            XDialog.alert(this, "Author can't be empty");
            cboAuthor1.requestFocus();
            return false;
        }

        String sl = txtAmount.getText();
        try {
            int soLuong = Integer.parseInt(sl);
            // SoLuong > 0
            if (soLuong <= 0) {
                XDialog.alert(this, "Amount must be greater than 0");
                txtAmount.requestFocus();
                return false;
            }
        } catch (Exception e) {
            XDialog.alert(this, "Amount must be number");
            txtAmount.requestFocus();
            return false;
        }

        if (s.getNgayNhap().equals("")) {
            XDialog.alert(this, "Date can't be empty");
            jDateChooser.requestFocus();
            return false;
        }
        if (s.getNoiDung().equals("")) {
            XDialog.alert(this, "Contents can't be empty");
            txtContent.requestFocus();
            return false;
        }
        if (s.getHinh().equals("")) {
            XDialog.alert(this, "Image can't be empty");
            lblHinh1.requestFocus();
            return false;
        }
        if (s.getUrl().equals("")) {
            XDialog.alert(this, "Url can't be empty");
            txtUrl.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * Do tat ca du lieu cua sach vao table
     */
    List<QuanLiSach> list = new ArrayList<>();

    private void load() {
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        try {
            list.clear();
            String keyword = txtFind.getText();
            if (!keyword.isEmpty()) {
                list = dao.selectByKeyword(keyword);
            } else {
                list = dao.select();
            }
            for (QuanLiSach s : list) {
                Object[] row = {
                    s.getMaSach(),
                    s.getTenSach(),
                    s.getLoai(),
                    s.getTacGia(),
                    s.getNXB(),
                    s.getNgayNhap(),
                    s.getSoLuong(),
                    s.getNoiDung(),
                    s.getHinh(),
                    s.getUrl()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
//            XDialog.alert(this, "Error data query!");
//            System.out.println(e);
            e.printStackTrace();
        }

    }

    List<String> listHinh = new ArrayList<>();

    public void loadcbbNXB() {
        NhaXuatBanDAO nxbdao = new NhaXuatBanDAO();
        modelNXB = (DefaultComboBoxModel) cboPub.getModel();
        List<NhaXuatBan> list = nxbdao.select();
        for (NhaXuatBan nxb : list) {
            modelNXB.addElement(nxb.getTenNXB());
        }
        cboPub.setModel(modelNXB);
    }

    public void loadcbbTenTheLoai() {
        TheLoaiDAO tlsdao = new TheLoaiDAO();
        modelTheLoai = (DefaultComboBoxModel) cboCategory.getModel();
        List<TheLoai> list = tlsdao.select();
        for (TheLoai tls : list) {
            modelTheLoai.addElement(tls.getTenTheLoai());
        }
        cboCategory.setModel(modelTheLoai);
    }

    public void loadcbbTacGia() {
        TacGiaDAO tgdao = new TacGiaDAO();
        modelTG = (DefaultComboBoxModel) cboAuthor1.getModel();
        List<TacGia> list = tgdao.select();
        for (TacGia tg : list) {
            modelTG.addElement(tg.getTenTacGia());
        }
        cboAuthor1.setModel(modelTG);
    }

    /**
     * Them sach moi -> load du lieu table -> Clear form
     */
    private void insert() {

        QuanLiSach model = getModel();
        if (!isValidate(model)) {
            return;
        }

        try {
            dao.insert(model);
            this.load();
            this.clear();
            XDialog.alert(this, "Add books successful!");
        } catch (Exception e) {
            XDialog.alert(this, "Add books fail!");
//            e.printStackTrace();
        }
    }

    /**
     * Cap nhat thong tin sach -> load du lieu table
     */
    private void update() {
        QuanLiSach model = getModel();
        try {
            dao.update(model);
            this.load();
            XDialog.alert(this, "Update books successful!");
        } catch (Exception e) {
            XDialog.alert(this, "Update books fail!");
//            e.printStackTrace();
        }
    }

    /**
     * Xoa sach da co
     */
    private void delete() {
        if (!XShare.isManager()) {
            XDialog.alert(this, "You do not have permission to delete Books!");
        } else {
            if (XDialog.confirm(this, "Are you sure to delete?")) {
                String masach = txtID.getText();
                try {
                    dao.delete(masach);
                    this.load();
                    this.clear();
                    XDialog.alert(this, "Delete books successful!");
//                    listHinh.clear();
                } catch (Exception e) {
                    XDialog.alert(this, "Delete books fail!");
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * Xoa trang form Set trang thai ve new
     */
    private void clear() {
//        this.setModel(new QuanLiSach());
        txtID.setText("");
        txtName.setText("");
        cboPub.setSelectedIndex(0);
        cboCategory.setSelectedIndex(0);
        cboAuthor1.setSelectedIndex(0);
//        jDateChooser.setDate(new Date(XDate.toString(model.getNgayNhap())));
        txtAmount.setText("");
        lblHinh1.setIcon(ResizeImage(""));
        txtContent.setText("");
        txtUrl.setText("");
        this.setStatus(true);
    }

    /**
     * Lay thong tin chuyen de sau khi click sach
     *
     */
    private void edit() {
        try {
            String macd = (String) tblDanhSach.getValueAt(this.index, 0);
            QuanLiSach model = dao.selectById(macd);
            if (model != null) {
                this.setModel(model);
                this.setStatus(false);
            }
        } catch (Exception e) {
            XDialog.alert(this, "Error data query!");
        }
    }

    /**
     * Do thong tin sach len form
     *
     * @param model la sach
     */
    private void setModel(QuanLiSach model) {
        stt = 0;
        txtID.setText(model.getMaSach());
        txtName.setText(model.getTenSach());
        cboPub.setSelectedItem(model.getNXB());
        cboCategory.setSelectedItem(model.getLoai());
        cboAuthor1.setSelectedItem(model.getTacGia());
        jDateChooser.setDate(new Date(XDate.toString(model.getNgayNhap())));
        lblHinh1.setToolTipText(model.getHinh());
//        System.out.println(model.getHinh());
        txtAmount.setText(model.getSoLuong() + "");

        txtContent.setText(model.getNoiDung());
//        System.out.println(listHinh.size());
        listHinh = new ArrayList<>();
//        System.out.println(model.getTenSach());
        listHinh = Arrays.asList(model.getHinh().split(","));
        if (listHinh.get(0) != null) {
            lblHinh1.setIcon(ResizeImage("src\\com\\poly\\image\\" + listHinh.get(stt)));
        } else {
            lblHinh1.setIcon(ResizeImage("src\\com\\poly\\image\\" + listHinh.get(stt)));
        }
        txtUrl.setText(model.getUrl());
    }

    private QuanLiSach getModel() {
        QuanLiSach model = new QuanLiSach();
        model.setMaSach(txtID.getText());
        model.setTenSach(txtName.getText());

        NhaXuatBanDAO nxbdao = new NhaXuatBanDAO();
        List<NhaXuatBan> listtt = nxbdao.selectByName(cboPub.getSelectedItem().toString());
        NhaXuatBan nxb = listtt.get(0);
        model.setNXB(nxb.getMaNXB());

        TheLoaiDAO tldao = new TheLoaiDAO();
        List<TheLoai> list = tldao.selectByName(cboCategory.getSelectedItem().toString());
        TheLoai theloaisach = list.get(0);
        model.setLoai(theloaisach.getMaTheLoai());

        TacGiaDAO tgdao = new TacGiaDAO();
        List<TacGia> listt = tgdao.selectByName(cboAuthor1.getSelectedItem().toString());
        TacGia tacgia = listt.get(0);
        model.setTacGia(tacgia.getMaTacGia());

        model.setNgayNhap(jDateChooser.getDate());
        System.out.println(txtAmount.getText());

        model.setSoLuong(Integer.parseInt(txtAmount.getText()));
        model.setNoiDung(txtContent.getText());
        model.setHinh(lblHinh1.getToolTipText());
        model.setUrl(txtUrl.getText());
        return model;
    }

    /**
     * Lay thong tin tu form
     *
     * @return la chuyen de
     */
    /**
     * Set trang thai cua form
     *
     * @param insertable la true set ve trang thai new, false chuyen sang trang
     * thai cap nhat
     */
    private void setStatus(boolean insertable) {
        txtID.setEditable(insertable);
        btnAdd.setEnabled(insertable);
        btnUpdate.setEnabled(!insertable);
        btnDelete.setEnabled(!insertable);

    }

    /**
     * Chon hinh
     */
    private void selectImage() {
        try {
            JFileChooser f = new JFileChooser("src\\com\\poly\\image");
            f.showOpenDialog(this);

            File file = f.getSelectedFile();
            if (XShare.saveLogo(file)) {
                // Hiển thị hình lên form
                lblHinh1.setIcon(ResizeImage(String.valueOf(XShare.readLogo(file.getName()))));
                lblHinh1.setToolTipText(file.getName());
            }
        } catch (HeadlessException ex) {
            System.out.println("No photo selected");
        }
    }

    private ImageIcon ResizeImage(String ImagePath) {
//        System.out.println(ImagePath);
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lblHinh1.getWidth(), lblHinh1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void remote() {
        if (stt < 0) {
            stt = listHinh.size() - 1;
        } else if (stt >= listHinh.size()) {
            stt = 0;
        }
        lblHinh1.setIcon(ResizeImage("src\\com\\poly\\image\\" + listHinh.get(stt)));
//        System.out.println(stt);
    }

    private void status(boolean st) {
        lblHinh1.setVisible(!st);
//        lblHinh2.setVisible(st);
    }

    XSSFWorkbook workbook = new XSSFWorkbook();

    private void print() {
        try {
            XSSFSheet sheet = workbook.createSheet("Manage Books");

            List<Object[]> list = dao.getQuanLiSach();

            int rownum = 0;
            Cell cell;
            Row row;
            // 

            row = sheet.createRow(rownum);

            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("Book ID");

            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("Name");

            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("Category");

            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("Author");

            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("Publisher");

            cell = row.createCell(5, CellType.NUMERIC);
            cell.setCellValue("Date Added");

            cell = row.createCell(6, CellType.NUMERIC);
            cell.setCellValue("Amount");

            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("Content");

            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("Image");

            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("Url");

            //DATA 
            for (int i = 0; i < list.size(); i++) {
                rownum++;
                row = sheet.createRow(rownum);

                cell = row.createCell(0, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 0));

                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 1));

                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 2));

                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 3));

                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 4));

                cell = row.createCell(5, CellType.NUMERIC);
                cell.setCellValue((Date) tblDanhSach.getValueAt(i, 5));

                cell = row.createCell(6, CellType.NUMERIC);
                cell.setCellValue((Integer) tblDanhSach.getValueAt(i, 6));

                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 7));

                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue((String) tblDanhSach.getValueAt(i, 8));

            }
            //PRINT
            chooseDirectoryToSave(workbook);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error Open File");
        }

    }

    private void chooseDirectoryToSave(Workbook workbook) {
        JFileChooser choose = new JFileChooser();
        int x = choose.showSaveDialog(null);
        if (x == JFileChooser.APPROVE_OPTION) {
            try {
                String file = choose.getSelectedFile().getAbsolutePath().toString() + ".xlsx";
                FileOutputStream outFile = new FileOutputStream(file);
                workbook.write(outFile);
                XDialog.alert(this, "Print file successful!!");
            } catch (IOException ex) {
                Logger.getLogger(DocGiaUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

}
