/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.ui;


import com.poly.utils.XDialog;
import com.poly.utils.XShare;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.ScrollPane;

/**
 *
 * @author CuongNX
 */
public class TrangChuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuJFram
     */
    private Color transparent;

    public TrangChuJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        simpleTitleBar1.init(this);
//        desktopMain.setPreferredSize(new Dimension(1154, 754));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlEmployee = new javax.swing.JPanel();
        lblEmployee = new javax.swing.JLabel();
        pnlReader = new javax.swing.JPanel();
        lblReader = new javax.swing.JLabel();
        pnlBooks = new javax.swing.JPanel();
        lblBook = new javax.swing.JLabel();
        pnlCategory = new javax.swing.JPanel();
        lblCategory = new javax.swing.JLabel();
        pnlAuthor = new javax.swing.JPanel();
        lblAuthor = new javax.swing.JLabel();
        pnlPub = new javax.swing.JPanel();
        lblPublisher = new javax.swing.JLabel();
        pnlViolation = new javax.swing.JPanel();
        lblViolation = new javax.swing.JLabel();
        pnlVouchers = new javax.swing.JPanel();
        lblVoucher = new javax.swing.JLabel();
        pnlStatistics = new javax.swing.JPanel();
        lblStatistics = new javax.swing.JLabel();
        pnlSetting = new javax.swing.JPanel();
        lblSetting = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        pnlChange = new javax.swing.JPanel();
        lblChange = new javax.swing.JLabel();
        desktopMain = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        simpleTitleBar1 = new javaswingdev.SimpleTitleBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jSplitPane1.setBackground(new java.awt.Color(205, 240, 234));

        jPanel3.setBackground(new java.awt.Color(246, 198, 234));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 620));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 520));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHome.setBackground(new java.awt.Color(246, 198, 234));
        pnlHome.setMinimumSize(new java.awt.Dimension(118, 20));
        pnlHome.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlHome.setLayout(new java.awt.BorderLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_home_office_36px_1.png"))); // NOI18N
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel12.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 50));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        pnlHome.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, -1));

        pnlEmployee.setBackground(new java.awt.Color(246, 198, 234));
        pnlEmployee.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlEmployee.setLayout(new java.awt.BorderLayout());

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_name_tag_36px.png"))); // NOI18N
        lblEmployee.setText("Manage Employee");
        lblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEmployeeMouseClicked(evt);
            }
        });
        pnlEmployee.add(lblEmployee, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 108, 200, -1));

        pnlReader.setBackground(new java.awt.Color(246, 198, 234));
        pnlReader.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReaderMouseClicked(evt);
            }
        });
        pnlReader.setLayout(new java.awt.BorderLayout());

        lblReader.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblReader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_manager_36px_1.png"))); // NOI18N
        lblReader.setText("Manage Readers");
        lblReader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReaderMouseClicked(evt);
            }
        });
        pnlReader.add(lblReader, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlReader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 54, 200, -1));

        pnlBooks.setBackground(new java.awt.Color(246, 198, 234));
        pnlBooks.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlBooks.setLayout(new java.awt.BorderLayout());

        lblBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_books_36px.png"))); // NOI18N
        lblBook.setText("Books Management");
        lblBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookMouseClicked(evt);
            }
        });
        pnlBooks.add(lblBook, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 161, 200, -1));

        pnlCategory.setBackground(new java.awt.Color(246, 198, 234));
        pnlCategory.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlCategory.setLayout(new java.awt.BorderLayout());

        lblCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_opened_folder_36px.png"))); // NOI18N
        lblCategory.setText("Category Management");
        lblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCategoryMouseClicked(evt);
            }
        });
        pnlCategory.add(lblCategory, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, 200, -1));

        pnlAuthor.setBackground(new java.awt.Color(246, 198, 234));
        pnlAuthor.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlAuthor.setLayout(new java.awt.BorderLayout());

        lblAuthor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuthor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_writer_male_36px.png"))); // NOI18N
        lblAuthor.setText("Author Management");
        lblAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAuthorMouseClicked(evt);
            }
        });
        pnlAuthor.add(lblAuthor, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 269, 200, -1));

        pnlPub.setBackground(new java.awt.Color(246, 198, 234));
        pnlPub.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlPub.setLayout(new java.awt.BorderLayout());

        lblPublisher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPublisher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPublisher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_lawyer_36px.png"))); // NOI18N
        lblPublisher.setText("Publisher Management");
        lblPublisher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPublisherMouseClicked(evt);
            }
        });
        pnlPub.add(lblPublisher, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlPub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 323, 200, -1));

        pnlViolation.setBackground(new java.awt.Color(246, 198, 234));
        pnlViolation.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlViolation.setLayout(new java.awt.BorderLayout());

        lblViolation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViolation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViolation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_foul_36px.png"))); // NOI18N
        lblViolation.setText("Violation Management");
        lblViolation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViolationMouseClicked(evt);
            }
        });
        pnlViolation.add(lblViolation, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlViolation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 377, 200, -1));

        pnlVouchers.setBackground(new java.awt.Color(246, 198, 234));
        pnlVouchers.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlVouchers.setLayout(new java.awt.BorderLayout());

        lblVoucher.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVoucher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVoucher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_membership_card_36px_1.png"))); // NOI18N
        lblVoucher.setText("Manage Loan Vouchers");
        lblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoucherMouseClicked(evt);
            }
        });
        pnlVouchers.add(lblVoucher, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlVouchers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 431, 200, -1));

        pnlStatistics.setBackground(new java.awt.Color(246, 198, 234));
        pnlStatistics.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlStatistics.setLayout(new java.awt.BorderLayout());

        lblStatistics.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblStatistics.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_analytics_36px.png"))); // NOI18N
        lblStatistics.setText("Statistics Report");
        lblStatistics.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblStatisticsMouseClicked(evt);
            }
        });
        pnlStatistics.add(lblStatistics, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlStatistics, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 485, 200, -1));

        pnlSetting.setBackground(new java.awt.Color(246, 198, 234));
        pnlSetting.setPreferredSize(new java.awt.Dimension(134, 50));
        pnlSetting.setLayout(new java.awt.BorderLayout());

        lblSetting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_settings_36px_1.png"))); // NOI18N
        lblSetting.setText("Setting");
        lblSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSettingMouseClicked(evt);
            }
        });
        pnlSetting.add(lblSetting, java.awt.BorderLayout.CENTER);

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        pnlSetting.add(jSeparator11, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(pnlSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 200, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 200, 4));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 200, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 211, 200, 4));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 200, 4));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 319, 200, 4));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 373, 200, 4));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 427, 200, 4));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 481, 200, 4));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 535, 200, -1));

        pnlChange.setBackground(new java.awt.Color(246, 198, 234));
        pnlChange.setLayout(new java.awt.BorderLayout());

        lblChange.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/icons8_password_36px_3.png"))); // NOI18N
        lblChange.setText("Change Password");
        lblChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChangeMouseClicked(evt);
            }
        });
        pnlChange.add(lblChange, java.awt.BorderLayout.CENTER);

        jPanel3.add(pnlChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 200, 50));

        jSplitPane1.setLeftComponent(jPanel3);

        desktopMain.setBackground(new java.awt.Color(205, 240, 234));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/library-removebg-preview.png"))); // NOI18N

        desktopMain.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopMainLayout = new javax.swing.GroupLayout(desktopMain);
        desktopMain.setLayout(desktopMainLayout);
        desktopMainLayout.setHorizontalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1053, Short.MAX_VALUE)
                .addContainerGap())
        );
        desktopMainLayout.setVerticalGroup(
            desktopMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(desktopMain);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);
        getContentPane().add(simpleTitleBar1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSettingMouseClicked
        // TODO add your handling code here:
        CaiDat cd = new CaiDat();
        cd.setVisible(true);
    }//GEN-LAST:event_lblSettingMouseClicked

    private void lblReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReaderMouseClicked
        // TODO add your handling code here:
        DocGiaUI docgia = new DocGiaUI();
        desktopMain.removeAll();
        docgia.setSize(1700, 2000);
        ScrollPane av = new ScrollPane();
        av.add(docgia);
        av.setSize(1200,1200);
        desktopMain.add(av);
        
//        desktopMain.add(docgia);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblReaderMouseClicked

    private void lblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEmployeeMouseClicked
        // TODO add your handling code here:
        NhanVienUI nv = new NhanVienUI();
        desktopMain.removeAll();
        nv.setSize(1700, 2000);
        desktopMain.add(nv);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblEmployeeMouseClicked

    private void lblBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookMouseClicked
        // TODO add your handling code here:
        QuanLiSachUI sach = new QuanLiSachUI();
        desktopMain.removeAll();
        sach.setSize(1700, 2000);
        desktopMain.add(sach);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblBookMouseClicked

    private void lblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCategoryMouseClicked
        // TODO add your handling code here:
        TheLoaiUI tl = new TheLoaiUI();
        desktopMain.removeAll();
        tl.setSize(1700, 2000);
        desktopMain.add(tl);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblCategoryMouseClicked

    private void lblAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAuthorMouseClicked
        // TODO add your handling code here:
        TacGiaUI tg = new TacGiaUI();
        desktopMain.removeAll();
        tg.setSize(1700, 2000);
        desktopMain.add(tg);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblAuthorMouseClicked

    private void lblPublisherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPublisherMouseClicked
        // TODO add your handling code here:
        NhaXuatBanUI nxb = new NhaXuatBanUI();
        desktopMain.removeAll();
        nxb.setSize(1700, 2000);
        desktopMain.add(nxb);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblPublisherMouseClicked

    private void lblViolationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViolationMouseClicked
        // TODO add your handling code here:
        ViPhamUI vp = new ViPhamUI();
        desktopMain.removeAll();
        vp.setSize(1700, 2000);
        desktopMain.add(vp);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblViolationMouseClicked

    private void lblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoucherMouseClicked
        // TODO add your handling code here:
        PhieuMuonUI pm = new PhieuMuonUI();
        desktopMain.removeAll();
        pm.setSize(1700, 2000);
        desktopMain.add(pm);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblVoucherMouseClicked

    private void lblStatisticsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStatisticsMouseClicked
        // TODO add your handling code here:
        ThongKeUI thongKeUI = new ThongKeUI();
        desktopMain.removeAll();
        thongKeUI.setSize(1700, 2000);
        desktopMain.add(thongKeUI);
        desktopMain.revalidate();
        desktopMain.repaint();
    }//GEN-LAST:event_lblStatisticsMouseClicked

    private void pnlReaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlReaderMouseClicked

    private void lblChangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChangeMouseClicked
        // TODO add your handling code here:
        this.openQuenMK();
    }//GEN-LAST:event_lblChangeMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        logoff();
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopMain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblAuthor;
    private javax.swing.JLabel lblBook;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblChange;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JLabel lblReader;
    private javax.swing.JLabel lblSetting;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblViolation;
    private javax.swing.JLabel lblVoucher;
    private javax.swing.JPanel pnlAuthor;
    private javax.swing.JPanel pnlBooks;
    private javax.swing.JPanel pnlCategory;
    private javax.swing.JPanel pnlChange;
    private javax.swing.JPanel pnlEmployee;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlPub;
    private javax.swing.JPanel pnlReader;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlStatistics;
    private javax.swing.JPanel pnlViolation;
    private javax.swing.JPanel pnlVouchers;
    private javaswingdev.SimpleTitleBar simpleTitleBar1;
    // End of variables declaration//GEN-END:variables

    
    private void openQuenMK() {
        if (XShare.authenticated()) {
            new DoiMatKhauUI(this, true).setVisible(true);
        } else {
            XDialog.alert(this, "Please login");
        }
    }
    
       /**
     * Mo form login Loi: Sau khi login thanh cong, se mo them 1 form polyPro ->
     * Bi thanh 2 form Khac phuc: Sau khi dang nhap thanh cong, quay tro lai
     * form cu hoac tat form cu va mo form moi Trang thai: Hoan thanh
     */
    private void openLogin() {
        if (XShare.authenticated()) {
            XDialog.alert(this, "You has login");
        } else {
            new DangNhapJDialog(this, true).setVisible(true);
            this.dispose();
        }
    }

    /**
     * Dang xuat khoi tai khoan -> mo form dang nhap
     */
    private void logoff() {
        if (XShare.authenticated()) {
            XShare.logoff();
            this.openLogin();
        } else {
            XDialog.alert(this, "Please login");
        }

    }
}
